### ISSUE TITLE
Errors when creating new Quasar project

### ISSUE THREAD

**Issue by LadIQe** [quasarframework/quasar#10340]
**Describe the bug**
There are problems when creating new quasar project. Eslint is reporting missing or not found types / functions / etc even they are imported and are working correctly. 

**Codepen/jsFiddle/Codesandbox (required)**
Just create new project `quasar create <name>` with typescript

**To Reproduce**
1. Create new project
2. Look at the console

**Expected behavior**
No errors

**Screenshots**
[link](https://ibb.co/FwGckn2)
[link2](https://ibb.co/vQVZLZP)

OS: MacOS 11
Node: 14.15.5
NPM: 6.14.11
Yarn: 1.22.10

**Additional context**
I created different project, maybe week ago and its working properly. No idea what changed

**Comment by MilosPaunovic** [comment]
Try running `yarn cache clean` and then a fresh dependency installation.

**Comment by LadIQe** [comment]
@MilosPaunovic hello, thank you for reply. Unfortunately, its not working

**Comment by jean-moldovan** [comment]
Also seeing some typescript related errors on the application start:
```
[webpack-dev-server] import/named: PropType not found in 'vue'
```

```
[webpack-dev-server] import/named: ActionTree not found in 'vuex'
```

and similar.

I'm on the latest quasar:
```
  "dependencies": {
    "@quasar/extras": "^1.10.10",
    "axios": "^0.21.1",
    "core-js": "^3.16.1",
    "dayjs": "^1.10.6",
    "quasar": "^2.0.3",
    "vue-i18n": "^9.0.0-beta.0",
    "vuex": "^4.0.1"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.15.0",
    "@quasar/app": "^3.0.4",
    "@types/node": "^16.4.13",
    "@typescript-eslint/eslint-plugin": "^4.29.1",
    "@typescript-eslint/parser": "^4.29.1",
    "eslint": "^7.32.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.24.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-vue": "^7.16.0",
    "npm-check-updates": "^11.8.3",
    "stylelint": "^13.13.1",
    "stylelint-config-standard": "^22.0.0"
  },

```

Removing and reinstalling node_modules did not help.

**Comment by hecsalazarf** [comment]
I started noticing it today.  Last week, didn't occur. Related to https://github.com/import-js/eslint-plugin-import/issues/2187.

A workaround: explicit `import type` as suggested by https://github.com/import-js/eslint-plugin-import/issues/2187#issuecomment-896253756

**Comment by Grawl** [comment]
Just got an error:

```
...

success Saved lockfile.
✨  Done in 66.19s.


 [*] Running eslint --fix to comply with chosen preset rules...


yarn run v1.22.10
$ eslint --ext .js,.ts,.vue ./ --fix

/Users/daniilpronin/Sites/create-quasar-2/src/components/OptionsComponent.vue
  16:27  error  PropType not found in 'vue'  import/named

...
```

after `npx @quasar/cli create`.

This code is causing an error:

```js
import { defineComponent, PropType } from 'vue'
                          ^^^^^^^^
```

I fixed it like this:

```js
import type { PropType } from 'vue'
import { defineComponent } from 'vue'
```

**Comment by capuvilla** [comment]
still showing errors to start new projects, both in version 1 and version 2

**Comment by capuvilla** [comment]
Problem occurs when selecting Standard as ESLint preset.

To use the standard, the typescript cannot be selected in the features.

**Comment by Grawl** [comment]
Why not? I use Standard with TypeScript and have no problems.

**Comment by vinicius73** [comment]
I've had the same problem, I've change a lot of import statements.

```ts
import { MyValue, MyType } from 'package-or-file'
```

```ts
import type { MyType } 'package-or-file'
import { MyValue } from 'package-or-file'
```

**Comment by Grawl** [comment]
Yes, it's a workaround

**Comment by rstoenescu** [comment]
This should not be reproducing (anymore). Verified with latest `@quasar/app` (v3.1.6) and `quasar` (v2.2.0).
