### ISSUE TITLE
Violation error Added non-passive event listener to a scroll-blocking

### ISSUE THREAD

**Issue by JokerMartini** [quasarframework/quasar#12822]
### What happened?

Created a new project and noticed that it produces tons of errors 'Added non-passive event listener to a scroll-blocking'. I'm not sure why this would be. I'm using the latest version of quasar for this project as of today it's the latest. 

### What did you expect to happen?

I dont expected to see so many errors.

### Reproduction URL

Not applicable

### How to reproduce?

1. Create a new project with cli
2. Run the project in dev electron
3. Check chrome console

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Electron Mode

### Platforms/Browsers

Electron

**Comment by robfordww** [comment]
![image](https://user-images.githubusercontent.com/24738409/158621171-1fd7651b-8fd2-453e-b10e-d5cf32d6608d.png)

I can confirm the same issue on a pretty new and basic app: 
 » Dev mode............... spa
 » Pkg quasar............. v2.6.0
 » Pkg @quasar/app-vite... v1.0.0-beta.3
 » Browser target......... edge99|chrome99

**Comment by MilosPaunovic** [comment]
Might come in handy:

[https://chromestatus.com/feature/5745543795965952](https://chromestatus.com/feature/5745543795965952)
[https://rbyers.github.io/scroll-latency.html](https://rbyers.github.io/scroll-latency.html)
[https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

**Comment by philippedasilva-orizone** [comment]
Hi, I'm getting this same issue and its repro is so simple to see: just open QBtn component page in the official Quasar documentation and you'll see a bunch of them in the console (verbose required).

From my quick research, I believe it has been introduced after this bug was reported: https://github.com/quasarframework/quasar/issues/12385
And @rstoenescu solved it with this commit: https://github.com/quasarframework/quasar/commit/672ed26b5632c10b25a68b2d1f3c8e7b101dc0fe

I believe it then generated this bug.

**Comment by pdanpdan** [comment]
So many comments and not even one that specifies OS/Browser + version

**Comment by philippedasilva-orizone** [comment]
> So many comments and not even one that specifies OS/Browser + version

In my case, I noticed it on my Macbook Air M1 running MacOS Monterey 12.3 on Chrome 99.0.4844.74

**Comment by pdanpdan** [comment]
Because I cannot reproduce it on chrome dev  on Linux and windows.
And on desktops it should not listen for touch events.

**Comment by philippedasilva-orizone** [comment]
> Because I cannot reproduce it on chrome dev on Linux and windows. And on desktops it should not listen for touch events.

I'm sorry but I just tried on Chrome 99.0.4844.82 on Windows (11) and I get the same warnings on the console (make sure to enable Verbose logging in the console to see them). If not, try a quick full refresh on the page as sometimes, I noticed that on first load, they do not appear somehow...

**Comment by JokerMartini** [comment]
I get this on windows desktop 
Operating System - Windows_NT(10.0.19042) - win32/x64
NodeJs - 14.17.0

**Comment by pdanpdan** [comment]
Ok, I found it, it's just on Qv2 because on Qv1 the listener is only attached when the device has touch.

But this is just a cosmetic difference, the main problem is that in order to allow preventing the touch event the listener must not be passive.

Maybe a way would be to check if there is a listener attached on QBtn and only the use non passive.

**Comment by philippedasilva-orizone** [comment]
Hi @pdanpdan could you point out where we should look at in the code so we can eventually submit a PR ? ;) thanks

**Comment by pdanpdan** [comment]
In here: https://github.com/quasarframework/quasar/blob/4a52a371e23a6519afe962f422068b4c7f715e39/ui/src/components/btn/QBtn.js#L87

But I don't understand the root cause of the problem, because in Qv1 I don't get the warnings.

**Comment by philippedasilva-orizone** [comment]
I don't know either but I strongly believe it is related to the commit I mentioned previously in order to solve a bug: it seems to me that it shows that we are replacing `OnTouchstartPassive` to `OnTouchstart`

**Comment by robert-hoffmann** [comment]
Definitely related to the q-btn

All pages that have a q-btn produce this error upon display

**Comment by JokerMartini** [comment]
Yeah this error still exists in all quasar projects i've been creating

**Comment by Sfinx** [comment]
Same here, Desktop Ubuntu 20.04 (no touch there !) , Chrome 101.0.4951.64 (Official Build) (64-bit), Quasar v2.6.6

**Comment by jaredthirsk** [comment]
Ditto: Brave 1.38.119, Chromium 101.0.4951.67, Windows 10, desktop with a touchscreen
 - Quasar v2.7.1
 - app-webpack 3.5.3

> And on desktops it should not listen for touch events.

What about desktops with touch screens ;)

**Comment by thomas-topway-it** [comment]
I'm also experiencing this error, on desktop, Linux, Quasar v2.7.1, it shows up only when the component/app is updated, not on loading, this could be related to the following piece of code 

    const onEvents = computed(() => {
      if (props.loading === true) {
        return {
          onMousedown: onLoadingEvt,
          onTouchstartPassive: onLoadingEvt,
          onClick: onLoadingEvt,
          onKeydown: onLoadingEvt,
          onKeyup: onLoadingEvt
        }
      }

      if (isActionable.value === true) {
        return {
          onClick,
          onKeydown,
          onMousedown,
          onTouchstart
        }
      }

(QBtn.js)

**Comment by 209** [comment]
Guys, could you fix it?)

<img width="474" alt="Снимок экрана 2022-08-10 в 23 37 43" src="https://user-images.githubusercontent.com/4629854/184015664-34a12af5-6d04-4634-802d-3696b89404e2.png">

**Comment by RobbeVorsselmans** [comment]
I'm still having this same problem...

Windows 10 Pro, no touchscreen, node v16.15.1, quasar v2.7.7

**Comment by Sazzels** [comment]
I am also experiencing this warning. 

```json
"node_modules/quasar": {
      "version": "2.8.3"
```

**Comment by Carleslc** [comment]
Same warnings in my Macbook Pro 2016, macOS Monterey 12.5.1, Chrome 104.0.5112.101
SPA quasar v2.8.3

**Comment by rstoenescu** [comment]
Fixed in https://github.com/quasarframework/quasar/commit/cb2c64dfb8518c6c03c5463d454f1b1eed5b0aec for Qv2.

Fix will be available in v2.8.5 and v1.21.0

**Comment by RobbeVorsselmans** [comment]
Thanks a lot!

**Comment by fardolieri** [comment]
Looks like this warning is still showing up whenever a QBtn with a `loading` prop is clicked. Is this expected?

**Comment by imvenx** [comment]
> Looks like this warning is still showing up whenever a QBtn with a `loading` prop is clicked. Is this expected?

Having same problem :loading prop is still giving warning.. in the meanwhile, any workaround that don't involve v-if/v-else?

![image](https://user-images.githubusercontent.com/115882542/217511848-51560899-2aa3-4ab7-89f1-606dc39c54cb.png)


> Fixed in [cb2c64d](https://github.com/quasarframework/quasar/commit/cb2c64dfb8518c6c03c5463d454f1b1eed5b0aec) for Qv2.
> 
> Fix will be available in v2.8.5 and v1.21.0

**Comment by pdanpdan** [comment]
You know, there are situations when that warning means exactly what it says.

**Comment by imvenx** [comment]
> You know, there are situations when that warning means exactly what it says.

?
It should be a way to set :loading event to passive

**Comment by pdanpdan** [comment]
It's a warning to check if what you did has a reason or not (in this case adding a non passive listener). And if you need to prevent default you need non passive

**Comment by imvenx** [comment]
> It's a warning to check if what you did has a reason or not (in this case adding a non passive listener). And if you need to prevent default you need non passive

yes, we need a way to set that event to passive, no point on having non passive loading event on btn by default.

**Comment by pdanpdan** [comment]
You mean you want the button to be still active while loading? Then just replace the content with a loading indicator

**Comment by imvenx** [comment]
> You mean you want the button to be still active while loading? Then just replace the content with a loading indicator

I mean exactly what OP means but for loading

**Comment by pdanpdan** [comment]
To summarize:
- if you want the button in loading state to not be active then the listeners must be not-passive (quasar behavior for l ii adding prop)
- if you want a button that is active but shows a loading indicator then change the content of the button to show a loading indicator

**Comment by imvenx** [comment]
> To summarize:
> 
>     * if you want the button in loading state to not be active then the listeners must be not-passive (quasar behavior for l ii adding prop)
> 
>     * if you want a button that is active but shows a loading indicator then change the content of the button to show a loading indicator

idk what you mean, If I create literally a `<q-btn loading />` component I get this warning, to me that looks like a bug, it should be a way to at least do loading.passive

**Comment by imvenx** [comment]
> To summarize:
> 
>     * if you want the button in loading state to not be active then the listeners must be not-passive (quasar behavior for l ii adding prop)
> 
>     * if you want a button that is active but shows a loading indicator then change the content of the button to show a loading indicator

btw I did the button with a spinner inside  on v-slot and still get warning message, idk if that's what you were saying, the only way to get around it is to do v-if/else with spinner instead of using loading, but that defeats the whole point of having a loading prop.

**Comment by pdanpdan** [comment]
Don't use the `loading` prop - use your own way to determine if it is loading
Make a codepen, please

**Comment by imvenx** [comment]
> Don't use the `loading` prop - use your own way to determine if it is loading Make a codepen, please

Forgot to mention that this bug only happens on electron, so can't make codepen

**Comment by Download** [comment]
> Ok, I found it, it's just on Qv2 because on Qv1 the listener is only attached when the device has touch.
> 
> But this is just a cosmetic difference, the main problem is that in order to allow preventing the touch event the listener must not be passive.
> 
> Maybe a way would be to check if there is a listener attached on QBtn and only the use non passive.

If you need the event to be non-passive, indicate so using the third parameter (set it to `true` I think). The warning is not about not using passive event handler, but about not using the third parameter to specify whether the event handler is passive or not. If you don't specify the third parameter, the browser will *assume* the event is non-passive and print this warning. If you specify the third parameter, the warning will disappear.

**Comment by Download** [comment]
Getting this warning with Quasar 

```
"quasar": "^2.16.4",
"nuxt-quasar-ui": "^2.1.2",
```

On a MacBook Pro
