### ISSUE TITLE
Dialog - can't open it on Safari if its not persistent

### ISSUE THREAD

**Issue by softal** [quasarframework/quasar#14779]
### What happened?

can't open Dialog on Safari if its not "persistent". same issue is on documentation page "https://quasar.dev/vue-components/dialog#introduction"

Safari Version 16.1 (18614.2.9.1.12)

### What did you expect to happen?

open dialog

### Reproduction URL

https://quasar.dev/vue-components/dialog#introduction

### How to reproduce?

1. go to documentation page https://quasar.dev/vue-components/dialog#introduction
2. try open Alert

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Safari

### Quasar info output

```Shell
nothing
```

**Comment by pdanpdan** [comment]
What quasar version, what safari on which device/os - for me it's working

**Comment by softal** [comment]
MacOS Ventura 13.00 (22A380) - updated yesterday (MacBook pro 14 M1 chip).
The problem related with Quasar v. 2.10.1 .  Problem is also on documentation page - can't open e.g Alert dialog but Confirm dialog is ok because is persistent...

**Comment by pdanpdan** [comment]
Ok. For Ventura I think you'll have to wait some time until someone can check

**Comment by piinodx** [comment]
same here.
MacOS Ventura, safari, without {persistent: true} option
Dialog is closed right after open (so we can't see dialog opened)

(Also, iOS with VoiceOver causes same.)

**Comment by pdanpdan** [comment]
Can you please check:
- https://v1.quasar.dev/vue-components/dialog#basic
- https://pdanpdan.github.io/quasar-docs/vue-components/dialog#basic
And report if any of them works on ventura?

**Comment by rstoenescu** [comment]
I'm on macOS Ventura with Safari Version 16.1 (18614.2.9.1.12).
Seems to be working correctly (both Quasar v1 and v2).

We need more info on how to reproduce?

**Comment by rstoenescu** [comment]
I've even turned VoiceOver on and still can't reproduce.

**Comment by softal** [comment]
I have checked both links and only 

- https://pdanpdan.github.io/quasar-docs/vue-components/dialog#basic

works fine in terms open the dialog without persistent.

But, on this site there are issues with open dialog for 

- page scroll

- with-containerized-qlayout

**Comment by jitza** [comment]
q-dialog isn't working for me on safari, even is I leave it open by default.... nothing is showing

**Comment by mgkimsal** [comment]
FWIW, I'm seeing this not on Ventura, but Monterey.  Safari 15.x.

This seemed to start within the last month, and... I may have quasar versions automatically bumping up some, so unsure what version may have stopped this.  But again, I'm seeing it on Monterey too.

And.. it only seems to happen when built for production.  When running in dev mode, this doesn't happen.

EDIT: rolling back to 2.9.1 definitely works.  2.9.2 sort of worked, but wasn't rendering internal data (but the dialog wasn't disappearing immediately).  2.9.1 still works. @softal can you try that?

**Comment by mgkimsal** [comment]
@rstoenescu 

https://quasar.dev/vue-components/dialog#sizing

Going there in safari, and clicking small/medium/large/etc - demonstrates the error for me, using Safari 15.6 (Monterey).  Also happens in my local projects, but not when I rolled back to 2.9.1

https://vimeo.com/769987657/e8c295905b

There's nothing happening in the console.  May be somewhat related to work done here: https://github.com/quasarframework/quasar/issues/14491 although the timing doesn't seem quite right.  I didn't first notice this until Nov 1, but was told it had started happening to us in mid October.  we hadn't locked package.json, so new builds were just getting new quasar versions, so I'm not sure when it was introduced, but definitely 2.9.1 revert works as it did before.  2.9.2 didn't have the flashing/closing, but wasn't rendering correctly (but that may be unrelated).  This may have been something in 2.10.0 ?

EDIT:
https://github.com/quasarframework/quasar/commit/18fe5fed5bd5da574379e5fcb0c58cb655e4f529

This shows
onFocusin: onBackdropClick 

added to the createComponent on dialog.js.  That *sounds* like safari would be treating the focusing of the component as something to trigger the backdropClick, which would also trigger a close?  Safari-only behavior it seems, but... is that helpful?

**Comment by softal** [comment]
Seems like everything is working now correctly !!! 

I have installed mac os update yesterday from Ventura 13.0 to 13.0.1 and the problem with Dialog gone. Checked with quasar v 2.10.1 (same on documentation page)

@mgkimsal dialog also works fine on version 2.9.1 and 2.9.2

**Comment by jitza** [comment]
yes it's now working.

**Comment by jitza** [comment]
yes it's now working. Thanks @softal 😊

**Comment by exninja** [comment]
This is odd as latest update works for some and not others.

Unfortunately, this still isn't working for me in latest Safari/Ventura - I've been on Safari 16.1 for a few days now.
(yes, persistent in q-dialog is a valid workaround for me too.)

Here's a working (ALERT and Bottomsheets succeeds to popup) codepen (copied straight off Quasar page for 2.10.0)
https://codepen.io/Exninja/pen/zYazeKJ

Here's a non-working codepen (ALERT and Bottomsheets not working)  
(copied straight off Quasar page for 2.10.1)
https://codepen.io/Exninja/pen/poKwGNd

Here's another non-working codepen (ALERT and Bottomsheets not working)  
(copied straight off Quasar page for 2.10.2)
https://codepen.io/Exninja/pen/JjZJxjm

* updated above codepens to include Bottomsheet also not working as noted by @mgkimsal

YMMV

**Comment by mgkimsal** [comment]
@exninja FYI, it's also happening on 'bottom sheet', for example.  Dunno if you could add those to your pen?

This isn't a 'dialog' issue so much as some UI change that is affect the closing state (or so it seems?)

**Comment by har1s1m** [comment]
I can confirm that non of the not persistent dialogs works in desktop. However it works as expected in mobile.

I can click on any example here using Safari and if it is not persistent it will not open 
https://quasar.dev/vue-components/dialog

Desktop Mac OS Ventura 13.0
Safari Version 16.1

**Comment by GitNomster** [comment]
I have same problem on Ventura 13.0.1 Safari 16.1 with Quasar 1.22.2.

**Comment by har1s1m** [comment]
> I'm on macOS Ventura with Safari Version 16.1 (18614.2.9.1.12). Seems to be working correctly (both Quasar v1 and v2).
> 
> We need more info on how to reproduce?

You can check any example https://quasar.dev/vue-components/dialog and if it is not persistent it doesn't open. Im using desktop safari 16.1 (Ventura 13.0)

**Comment by ddekleer** [comment]
This is what I noticed with a Vite standalone setup in Safari/epiphany-browser when setting up a q-dialog:
* In the versions after 2.10.0, the dialog opens only when switching to another screen and back (after completely losing focus). On an iPad it opens only after going back to the home screen, and going back to the browser again.
* This might to be related to the behaviour in the `renderPortal` and `renderPortalContent` methods in QDialog. Seems the QDialog goes trough all the transisitions, but they just do not happen in Webkit browsers it seems. The element is not being rendered until completely removing focus (switching to another screen) and focusing again.
* The `@hide` event can be triggered right away on clicking a button to show a simple dialog.
* Seems this issue might be related to how focus/clicks/transitions are being handled in Webkit browsers?

Strange thing is that the Quasar docs examples does seem to work in these browsers, but when copy pasted to my own setup it doesn't work. Dependencies:

```
  "dependencies": {
    "axios": "^0.27.2",
    "vue": "^3.2.37",
    "pinia": "^2.0.22",
    "pinia-plugin-persistedstate": "^2.4.0",
    "@quasar/extras": "^1.0.0",
    "@quasar/vite-plugin": "^1.2.3",
    "quasar": "2.10.2",
    "vue-router": "^4.0.0",
    "lodash": "^4.17.21",
    "vue-underscore": "^0.1.4",
    "vue-i18n": "^v9.3.0-beta.6",
    "vee-validate": "^4.6.9",
    "@vee-validate/i18n": "^4.6.10",
    "@vee-validate/rules": "^4.6.10",
    "scroll-into-view-if-needed": "^2.2.29",
    "uuid": "^9.0.0",
    "vue-deepunref": "^1.0.1"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.1.0",
    "vite": "^3.1.3",
    "babel-eslint": "^10.1.0",
    "cypress": "^7.2.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-cypress": "^2.11.3",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-prettier-vue": "^3.1.0",
    "eslint-plugin-vue": "^7.15.1",
    "prettier": "^2.3.2",
    "sass": "~1.32.12",
    "postcss": "^8.4.14"
  }
```

**Comment by softal** [comment]
unfortunately problem with dialog came back. If dialog has not persistent attribute, its not appear. 
Mac OS Ventura 13.0.1 Safari Version 16.1 (18614.2.9.1.12) - i've just restarted laptop.
Quasar v. 2.10.2 (problem also refers to documentation page )

**Comment by 3m1n3nc3** [comment]
> This is odd as latest update works for some and not others.
> 
> Unfortunately, this still isn't working for me in latest Safari/Ventura - I've been on Safari 16.1 for a few days now. (yes, persistent in q-dialog is a valid workaround for me too.)
> 
> Here's a working (ALERT and Bottomsheets succeeds to popup) codepen (copied straight off Quasar page for 2.10.0) https://codepen.io/Exninja/pen/zYazeKJ
> 
> Here's a non-working codepen (ALERT and Bottomsheets not working) (copied straight off Quasar page for 2.10.1) https://codepen.io/Exninja/pen/poKwGNd
> 
> Here's another non-working codepen (ALERT and Bottomsheets not working) (copied straight off Quasar page for 2.10.2) https://codepen.io/Exninja/pen/JjZJxjm
> 
> * updated above codepens to include Bottomsheet also not working as noted by @mgkimsal
> 
> YMMV

I downgraded my quasar version to 2.10.0 after reading this comment, seems to be the only thing that worked. 
I tried older versions also without success. I'll have to stick to 2.10.0 until a fix is available.

**Comment by TodesRitter** [comment]
Same problem here Ventura 13.0.1, Safari 16.1

**Comment by piinodx** [comment]
Same problem still

Quasar 2.11.1
Ventura 13.1
iOS 16.2 (once occurs with voiceOver, dialog won't show with any way eg. refresh)

also qSelect (behavior="dialog") options dialog has same problem.

when I've look into it with safari developer, Dialog element has added to bottom of page, and removed right away. (seems like background touch (impersistent) event has fired with some reason)

**Comment by GitNomster** [comment]
problem still exists in quasar v1.22.3. It often happens when i open browser console

**Comment by EranClientside** [comment]
I also have this issue, both in my app and the documentation. (Basic - Alert example)
```
Quasar: v1.22.2
macOS: Monterey 12.6
Safari: 16.0 (17614.1.25.9.10, 17614)
```

**Comment by eranshmil** [comment]
I also have this issue, both in my app and the documentation. (Basic - Alert example)
```
Quasar: v1.22.2
macOS: Monterey 12.6
Safari: 16.0 (17614.1.25.9.10, 17614)
```

**Comment by boid-com** [comment]
I'm seeing this problem using quasar 2.11.4 with @quasar/app-vite 1.1.3

Opens once then won't open again
`Dialog.create({ message: "hi" })`
`Dialog.create({ persistent: true, component: MyComponent })`

Works correctly:
`Dialog.create({ message: "hi", persistent: true })`

Tested working properly in FF/Chrome/Brave, seems to be an issue with Safari exclusively.

The issue seems to be inconsistent, some modals work as expected always but most fail, maybe related to some subtle differences of the wrapped components. 

Normal Dialog with just a text message and persistent:true seems to always work.

TEMP FIX: Downgrading to quasar@2.10.0 solved the problem for me

**Comment by censoredp** [comment]
Same here. `Mac OS 12.6 M1, Safari 16.0, Quasar 2.10.2, Dev SSR mode`.
Trace for dialog closing goes through `Ripple.start` and `showRipple` to `onBackdropClick` with `e = FocusEvent`.

First noticed problem on physical iPhone, after some debugging (no code was changed) problem gone on iPhone and still exists only on Mac.

Problem gone also on desktop Safari after restarting the server or upgrading Quasar to 2.11.4 (sorry for performing both in one turn).

**Comment by 3m1n3nc3** [comment]
How is? the quasar team not looking into this issue, I'm looking to temporarily drop support for Safari because of this issue.

**Comment by rstoenescu** [comment]
Should work correctly with Quasar v2.11.5 and v1.22.5.
Just to be clear: this is a bug in Safari itself, but regardless, we've done a workaround for it.
