### ISSUE TITLE
Slider step 0.01 return 0.7400000000000000002 instead of just 0.74 (also with some other values)

### ISSUE THREAD

**Issue by nielslucas** [quasarframework/quasar#1736]
So the title said it all.

I have a slider with a step of 0.01 but sometimes i get a value returned like 0.7400000000002. (dident count the zero's) atm am using quasar version 0.14.9

code:
```
<q-slider v-model="myModal" :min="0" :max="100" :step="0.01" label color="light-green" />

<q-field class="percentage">
           <q-input v-model="myModal"
                     type="number"
                     :decimals="2"
                     :step="0.01"
                     :min="0"
                     :max="100"
                     suffix="%"
                     align="right"
                    />
</q-field>
```

result:
![naamloos](https://user-images.githubusercontent.com/7912307/37211974-fbd2422a-23ad-11e8-93b5-1bbbe024cf89.png)

Expected value:
17.74 (this case)

This isn't with every value. Just try this just slide and you will notice it quickly enough. Like 2 of 10 value's

**Comment by rstoenescu** [comment]
Hi,

This is fixed in 0.15. Please take some time to read the upgrade guide.

**Comment by hawkeye64** [comment]
I found in 0.16 the label still shows up to 5 decimal places. If you want to adjust this, you can do the following with `label-value`:
```
          <q-slider
            v-model="currentTime"
            :min="0"
            :max="duration"
            label-always
            markers
            square
            :label-value="String(Math.round(currentTime * 10) / 10)"
          />
```

**Comment by rstoenescu** [comment]
@hawkeye64 But in your case you're the one telling what the label is! Beware of the floating point presision error in JS: https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
