### ISSUE TITLE
[@quasar/babel-preset-app] core-js warning when building

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar#4205]
This will not break your app. It will continue to work as expected.
core-js package will get upgraded in `@quasar/app` 1.0.0-rc.2

> WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
>
> You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

**Comment by rstoenescu** [comment]
Fixed in `@quasar/app` 1.0.0-rc.2

**Comment by rmetcalf9** [comment]
I am using 1.0.0-rc.2 and I am still getting exactly this message:


```
rjmetcal@ict-rjmetcal:~/sideGIT/saas_thumbsum/webapp$ quasar dev

 Dev mode.......... spa
 Pkg quasar........ v1.0.0-rc.2
 Pkg @quasar/app... v1.0.0-rc.1
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +3ms
 app:webpack Extending SPA Webpack config +380ms
 app:generator Generating Webpack entry point +4ms
 app:dev-server Booting up... +2ms


  SPA ██████████                building [40%] 9/12 modules 3 active


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:


  SPA █████████████████████████ [100%] in ~7s



 DONE  Compiled successfully in 6976ms                                                                                                                                                                     12:50:42


 N  App dir........... /home/IC.AC.UK/rjmetcal/sideGIT/saas_thumbsum/webapp
    App URL........... http://localhost:8080/
    Dev mode.......... spa
    Pkg quasar........ v1.0.0-rc.2
    Pkg @quasar/app... v1.0.0-rc.1
  
 app:dev-server Opening default browser at http://localhost:8080/ +7s

^C
rjmetcal@ict-rjmetcal:~/sideGIT/saas_thumbsum/webapp$ quasar info

Operating System - Linux(4.18.0-22-generic) - linux/x64
NodeJs - 8.16.0

Global packages
  NPM - 6.9.0
  yarn - Not installed
  @quasar/cli - 1.0.0-rc.2
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.2 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.1 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.0 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - ict-rjmetcal
  wlp1s0 - 146.169.160.82
  enxc46516f16b40 - 155.198.139.70
  docker_gwbridge - 172.18.0.1

```

Do I need to do something to apply this fix?

**Comment by rmetcalf9** [comment]
Forgive the stupid question, I worked out I needed to run:
`sudo quasar upgrade
`then
`sudo quasar upgrade -i`
