### ISSUE TITLE
q-layout issue on iOS safari

### ISSUE THREAD

**Issue by stephentuso** [quasarframework/quasar#422]
I have a template similar to this:

```html
<q-layout>
  <div slot="header" class="toolbar">
    ...
  </div>

  <div class="layout-view">
    <q-infinite-scroll>
      ...
    </q-infinite-scroll>
  </div>
</q-layout>
```

This works fine in desktop browsers and Android, but on iOS 9 Safari the content of the infinite scroll is covered by the toolbar. I'm using a flexbox based grid in the infinite scroller. Is this an issue with the framework? Or could there be something wrong on my end?

**Comment by rstoenescu** [comment]
Already fixed in future v0.13.2 or edge version. Can you confirm with edge version? http://quasar-framework.org/guide/quasar-nightly-build.html

**Comment by stephentuso** [comment]
@rstoenescu I installed the edge version and I'm still having the same issue. Works on iOS 10.2 but not on 9.3. Doesn't `q-layout` just use flexbox? Seems like iOS 9.3 is missing support for something, but according to [caniuse](http://caniuse.com/#feat=flexbox), flexbox should be fully supported. I'm trying to inspect it to get some more details but I'm having issues with Safari's remote debugger.

**Comment by rstoenescu** [comment]
Please do help. Need some assistance as I'm currently focusing on v0.14. Layout component indeed uses flexbox and theoretically it should just work.
