### ISSUE TITLE
[V1] - button dropdown menu doesn't show content in IE11

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar#4253]
### Software version

```
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.15.3

Global packages
  NPM - 6.4.1
  yarn - 1.13.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.3 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.4 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  quasar-app-extension-ide-helper - 0.0.5 -- Quasar framework extension which enables IDE features like autocomplete by generating helper files for IDE to index.
  @quasar/quasar-app-extension-icon-factory - 1.0.0-rc.2 -- A Quasar CLI Extension
```

### JsFiddle
IE11 not supported in JsFiddle but you can try it on Quasar docs page:
[https://quasar.dev/vue-components/button-dropdown](https://quasar.dev/vue-components/button-dropdown)

### What did you get as the error?
Dropdown menu doesn't appear when clicked on the expand icon.
Problem was first spotted on my PC while developing an app. 
```quasar build``` and ```quasar dev``` has the same result.

### What were you expecting?
Show the content

### What steps did you take, to get the error?
Open IE11 and click on Basic DROPDOWN BUTTON:
![image](https://user-images.githubusercontent.com/37825539/58635515-616ef600-82ee-11e9-84c1-9db1329c9b51.png)
Chrome result:
![image](https://user-images.githubusercontent.com/37825539/58635566-7ea3c480-82ee-11e9-90d3-df309ba036ba.png)

**Comment by rstoenescu** [comment]
Hi, this was fixed in quasar 1.0.0-rc.4. Please upgrade to it. Thanks.

**Comment by m0jimo** [comment]
I have upgraded (just now) but still the same result as described above. 
Screenshots were taken from the online docs few minutes ago which is rc.4 and it doesn't work either.

**Comment by aoltra** [comment]
Hi!

I don't know if it's related. but I'm having the same problem in an electron app. I checked that the error appears since version 1.0.0-beta.24 (in 1.0.0-beta.23 everything worked ok)

**Comment by blaluc** [comment]
Any news about this blocking issue?

It seems that there are quite a number of issues with IE11, after the latest quasar upgrade :-(
For example, below is how the buttons are displayed in the getting started site:
![image](https://user-images.githubusercontent.com/4599417/59348644-ece97d80-8d17-11e9-9f75-9f432a26df22.png)

**Comment by m0jimo** [comment]
I'd say it is not related to the DropDown button. It would be better to report it as a new issue. Screenshot is from the documentation page. Do you know which component is used for this navigation? I can confirm that I see the same in my IE11 as you posted.

Generally I don't think that 
> there are quite a number of issues with IE11

Issues related to IE11 are always quickly fixed and I admire the job Quasar team does for IE11 support. 

I'm sure Q team will be happy to hear more about issues you have discovered in IE11.

**Comment by blaluc** [comment]
@m0jimo I totally agree with you about  the great job of the Quasar team.

I know that providing a full support for IE11 it's not a trivial thing, but there are some stange behaviors that are quite evident, specially if they are immediately visible in the documentation site (perhaps, before publishing a new release it would be advisable to navigate the doc site with IE11). 

Following your suggestion I've just opened some separate issues.

**Comment by rstoenescu** [comment]
Fix will be available in rc.5
