### ISSUE TITLE
Compilation failure "dependency not found" objectSpread2

### ISSUE THREAD

**Issue by mpacary** [quasarframework/quasar#4543]
**Describe the bug**
When doing `quasar dev` for a fresh empty project, I always get this error when the build process is around 50% done:
```
 ERROR  Failed to compile with 6 errors                                                                                                                         3:50:15 PM

This dependency was not found:

* C:\...\test\node_modules\@babel\runtime-corejs2/helpers/objectSpread2 in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/components/btn/QBtn.js and 4 others

To install it, you can run: npm install --save C:\...\test\node_modules\@babel\runtime-corejs2/helpers/objectSpread2
```
Build process then freezes.

Doing CTRL+C then running the suggested `npm install` command from the error message fails (could not install / error code ENOENT / -4058 / no such file or directory). Tried as well with `yarn add`, no luck.

I get a very similar issue & error message about "missing dependency .../objectSpread2" when running `quasar build`

**Codepen/jsFiddle/Codesandbox (required)**
N/A (CLI only)

**To Reproduce**
1. Create empty project with Quasar 1.0.3 & Quasar CLI 1.0.0 (`quasar create`), choosing default options
2. Go in project directory and run `quasar dev`

**Expected behavior**
Finish compilation/build, start browser etc. instead of giving an error message

**Platform (please complete the following information):**
OS: Win 10 & Mac OS 10.14.5
Quasar info gives (on Win) :
```

Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.16.0

Global packages
  NPM - 4.4.1
  yarn - 1.15.2
  @quasar/cli - 1.0.0
  cordova - 7.1.0

Important local packages
  quasar - 1.0.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.0 -- Quasar Framework local CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  ...
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
```

**Comment by mpacary** [comment]
More info on Mac OS :

When choosing npm for installation => exact same problem as reported above
When choosing yarn for installation => build process freezes at 0%

**Comment by nothingismagick** [comment]
please update to @quasar/app v1.0.1 -> babel had a regression that's been
fixed.

**Comment by iperiago** [comment]
Unfortunately still experiencing the problem even after upgrading quasar to v1.0.1.

Both `quasar build` and `quasar dev` fail on existing projet (there were working before) with errors in every Quasar component - example :  

```
ERROR in ./node_modules/quasar/src/components/layout/QFooter.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
  ReferenceError: Unknown helper objectSpread2
```

Platform : Macos with npm

**Comment by rstoenescu** [comment]
Delete node_modules folder and yarn.lock / package-lock.json and install again.

**Comment by iperiago** [comment]
it worked. thanks for the fix and the amazing work on this great framework

**Comment by mpacary** [comment]
Thanks for your reactivity. I confirm that this is fixed with @quasar/app v1.0.1 (now default version with `quasar create`)

**Comment by rstoenescu** [comment]
This is how we roll for critical issues.

**Comment by Grawl** [comment]
Just faced this issue with Quasar v2 / Vue 3 and removing `yarn.lock` is a solution.
