### ISSUE TITLE
DNS Serialnumber pdns08.domaincontrol.com for quasar.dev should be updated

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#5628]
It seems during the dns update process for

quasar.dev
and www.quasar.dev

there where for short time a resolution issue.

After solving that, the serialnumber for the entries for quasar.dev was not upgraded (changed).

The serial number on pdns07 / pdns08.domaincontrol.com  is still on 2019110807.

Many dns server would not update, if this is still pointing to this "older" serialnumber.

Please upgrade (once again) the quasar.dev to the new ip adress and also the serial number should be bumped up to a newer one.

more details can be reached by dnslookup and set type=ANY

www.quasar.dev has all updates , but not the quasar.dev .. so its no ttl issue.

dns server which use dns over ssl / https where updated , but many (50 %+) dns server are
still working with the old (not ssl) dns versions ..

**Comment by ibrainventures** [comment]
in this second ... (5 mins later after my issue sending) the dns here has updated .. :-) .. 
didnt know why .. but sometimes the internet is like magic ...

**Comment by rstoenescu** [comment]
Hi,

I've just triggered a DNS change 1 minute ago.  Investigated and tried a lot of things and nothing worked. Hopefully this would settle it.
Thanks for writing this ticket!

**Comment by ibrainventures** [comment]
hi @rstoenescu 

it seems that the **quasar-framework.org** domain (also without www.) is pointing to the old ip.  The wwwquasar-framework.org. has its updates.

there was no dns update invoked, so i think it needs your hands.

mostly - e.g- 

https://www.codeinwp.com/blog/vue-ui-component-libraries/

are linking to that domain and showing broken links ...

**Comment by rstoenescu** [comment]
It should work now.

**Comment by ibrainventures** [comment]
actually there is still no change on the primary dns server - where the updated changes should first seeable.

you can check them easy self:

`nslookup`

then (switching to the primary dns for this domain)

`server pdns07.domaincontrol.com`

then (get information about the domain e.g. )

`quasar-framework.org`

if you want see more details

`set type=any`

still points to the old : 34.65.228.161

**Comment by rstoenescu** [comment]
I was so focused on quasar.dev that I completely disregarded that you mentioned the old quasar-framework.org domain :) That should work too now.
