### ISSUE TITLE
assets not resolve with ~ symbol

### ISSUE THREAD

**Issue by elselapatha** [quasarframework/quasar#5701]
assets images not resolve after upgrade to quasar _**1.4.5**_ and app _**1.3.0**_
inspect the source and code is show like `<img src="[object Module]" style="width: 30vw; max-width: 150px;">`

**Comment by ggeorgiev92** [comment]
I have the same issue. Issue occur when quasar/app is 1.3.0 version (maybe some of updated dependencies). I downgrade my app to last stable 1.2.4 and everything work like a charm.
![unknown](https://user-images.githubusercontent.com/26670461/69673942-26cef600-10a4-11ea-9968-38319c4f0e2a.png)

**Comment by jacksonGross** [comment]
I think it could be related to https://github.com/quasarframework/quasar/pull/5621

**Comment by 0xDarker** [comment]
+1

**Comment by elselapatha** [comment]
> I have the same issue. Issue occur when quasar/app is 1.3.0 version (maybe some of updated dependencies). I downgrade my app to last stable 1.2.4 and everything work like a charm.
> ![unknown](https://user-images.githubusercontent.com/26670461/69673942-26cef600-10a4-11ea-9968-38319c4f0e2a.png)

Thanks. Solve the issue

**Comment by miladmeidanshahi** [comment]
the same problem please update @rstoenescu

**Comment by pdanpdan** [comment]
Can you please check file-loader's version on working and not working app (1.2.4 and 1.3.0) with `npm list file-loader` and report back?

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting! Fixed in "@quasar/app" v1.3.1. Please upgrade to it.

**Comment by 0xDarker** [comment]
I upgrade to "@quasar/app" v1.3.1 but this issue still exists. @rstoenescu

**Comment by rstoenescu** [comment]
@0xDarker it's impossible. make a cleanup of node_modules and yarn.lock/package-lock.json and yarn/npm install again. Also make sure that you haven't manually added url-loader or file-loader to your project.

**Comment by 0xDarker** [comment]
> @0xDarker it's impossible. make a cleanup of node_modules and yarn.lock/package-lock.json and yarn/npm install again. Also make sure that you haven't manually added url-loader or file-loader to your project.

Sorry it ’s really because I added file-loader, thanks

**Comment by rstoenescu** [comment]
No prob. Glad it's working for you too now.

**Comment by Propaganistas** [comment]
I deleted node_modules and yarn.lock, and yet I'm still experiencing this issue from v1.3.1 and onwards.

**Comment by rstoenescu** [comment]
@Propaganistas this has been fixed 101%. are you sure that you are running latest q/app? what does it say when you run quasar dev or build right at the top in terminal?

**Comment by Propaganistas** [comment]
@rstoenescu Thanks for bearing with me. I'm using another build runner based on webpack with some sensible defaults preset (so not Quasar builder). I tracked it down to the defaults not including  `esModule: false` in file-loader's options. Adding that fixed it.
