### ISSUE TITLE
q-btn display problem

### ISSUE THREAD

**Issue by yinchuanyue** [quasarframework/quasar#5843]
**Describe the bug**
When I upgraded quasar to the latest version (v1.3.0 to v1.5.7), all q-btn in my quasar project were on the mobile side, and the mac display was particularly long, normally displayed in the linux/windows chrome browser. Then I upgraded the project step by step from v1.3.0, when the upgrade to v1.5.0 occurred with the problem
**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Operating System - Linux(4.19.0-6-amd64) - linux/x64
NodeJs - 10.17.0

Global packages
  NPM - 6.13.2
  yarn - 1.19.2
  @quasar/cli - 1.0.2
  cordova - Not installed

Important local packages
  quasar - 1.5.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.2.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js

**Additional context**

**Comment by pdanpdan** [comment]
Can you please explain what does this mean?
`all q-btn in my quasar project were on the mobile side, and the mac display was particularly long, normally displayed in the linux/windows chrome browser`

**Comment by yinchuanyue** [comment]
First of all, thank you for your answer and apologize for my ability to express myself. When I access my quasar project through chrome browser under windows or linux, the page appears normally. But through mobile browser, mac browser(Safari) access, q-btn height is very large



`
<template>
  <div>
    <self-card :title="$t('commonCmd')">
      <q-card-section class="q-pa-sm">
        <div class="text-subtitle1 text-left">dome:</div>
        <div
          class="text-left"
          v-if="this.devices().includes('dome')"
        >
          <q-toggle
            class="q-pl-sm q-mr-md"
            false-value="Close"
            true-value="Open"
            :label="`dome is ${getDomeState}`"
            v-model="domestatus"
            @input="domecmd"
          ></q-toggle>
          <q-btn
            @click="domeStop"
            size="sm"
            push
            :label="$t('stop')"
            color="red"
            no-caps
          ></q-btn>
        </div>
        <div
          v-else
          class="q-pl-md text-red text-left"
        >{{$t('disconnected')}}</div>
      </q-card-section>
      <q-separator />
      <q-card-section class="q-pa-sm text-left">
        <div class="text-subtitle1 text-left">telescope:</div>
        <q-form
          v-if="this.devices().includes('telescope')"
          @submit="cmdTelescope"
        >
          <q-item dense>
            <q-input
              class="q-mr-md"
              v-model="teles_name"
              color="info"
              :label="$t('DandC')"
              readonly
              style="width:80px; padding:0px 2px 7px 2px"
            />
            <q-select
              class="q-mr-sm"
              v-model="curr_command"
              :options="commandlist"
              color="info"
              :label="$t('commandcontent')"
              hint
              @input="getArgsList"
              style="min-width:110px; padding:0px 2px 7px 2px"
            />
            <span class="self-center">
              <q-btn
                push
                class="q-ml-sm q-mt-sm"
                color="secondary"
                size="sm"
                type="submit"
                :label="$t('send')"
                no-caps
                style="min-width:50px"
              />
            </span>
          </q-item>
          <q-item
            v-if="this.curr_command"
            dense
          >
            <q-input
              class="q-ml-md"
              dense
              v-model="item.value"
              :label="item.name"
              v-for="(item , index) in argslist"
              :key="index"
              style="max-width:200px"
              lazy-rules
              :rules="[ val => val && val.length > 0 || $t('notinput')]"
            ></q-input>
          </q-item>
        </q-form>
        <div
          v-else
          class="q-pl-sm text-red text-left"
        >{{$t('disconnected')}}</div>
      </q-card-section>
      <q-separator />
      <q-card-section class="q-pa-sm">
        <div class="text-subtitle1 text-left">focus:</div>
        <div
          class="text-left q-ml-md"
          q-pa-sm
          v-if="this.devices().includes('focus')"
        >
          <q-btn
            class="q-mr-xl"
            @click="findHome"
            size="sm"
            push
            label="home"
            color="secondary"
            no-caps
          >
            <q-tooltip>{{$t('findhome')}}</q-tooltip>
          </q-btn>
          <q-btn
            @click="focusStop"
            size="sm"
            push
            :label="$t('stop')"
            color="red"
            no-caps
          ></q-btn>
          <q-form
            class="q-mt-md"
            @submit="setPos"
          >
            <span>Position:</span>
            {{getfocusPosition}}
            <q-item
              dense
              style="padding:0"
            >
              <q-input
                v-model="tar_posi"
                dense
                style="max-width:150px"
              />
              <q-btn
                class="q-ml-md"
                type="submit"
                size="sm"
                push
                label="position"
                color="secondary"
                no-caps
              ></q-btn>
            </q-item>
          </q-form>
        </div>
        <div
          v-else
          class="q-pl-sm text-red text-left"
        >{{$t('disconnected')}}</div>
      </q-card-section>
      <q-separator />
      <q-card-section class="q-pa-sm">
        <div class="text-subtitle1 text-left">CAM1:</div>
        <div>
          <div
            class="text-left q-pa-sm"
            v-if="this.devices().includes('CAM1')"
          >
            <span class="q-mr-sm">{{$t('targettemp')}}:</span>
            <span>{{getcam1TargetTemp()}}</span>
            <br />
            <span class="q-mr-sm">{{$t('temphot')}}:</span>
            <span>{{getcam1TempHot()}}</span>
            <br />
            <span class="q-mr-sm">{{$t('tempcold')}}:</span>
            <span>{{getcam1TempCold()}}</span>
            <br />
            <q-toggle
              v-model="cam1_cool"
              true-value="coolon"
              false-value="cooloff"
              left-label
              :label="getlabel()"
              checked-icon="check"
              color="green"
              unchecked-icon="clear"
              @input="cameraCool"
            ></q-toggle>
            <div>
              <span>{{$t('exposetime')}}</span>
              <span class="cursor-pointer">
                {{getcam1Exptime()}}
                
              </span>
              <q-item dense>
                <q-input
                  dense
                  v-model="cam1Exptime"
                  style="max-width:200px"
                  @blur="changeExptime"
                ></q-input>
                
                <q-btn
                  class="q-ml-md"
                  push
                  no-caps
                  size="xs"
                  label="Expose"
                  color="secondary"
                  @click="camExpose"
                ></q-btn>
              </q-item>
            </div>
          </div>
          <div
            v-else
            class="q-pl-sm text-red text-left"
          >{{$t('disconnected')}}</div>
        </div>
      </q-card-section>
    </self-card>
  </div>
</template>
<script>
import httpApiConfig from '../api/api_teles'
const API = httpApiConfig.api
import { mapState } from 'vuex'
export default {
  name: 'common-cmd',
  components: {
    SelfCard: () => import('components/SelfCard')
  },
  data () {
    return {
      argslist: [],
      domestatus: this.getDomeStatus(),
      teles_name: 'telescope',
      curr_command: '',
      telescopecmd: [
        'findhome',
        'trackstar',
        'connect',
        'slewazel',
        'trackstar_no_param',
        'trackstarsimple'
      ],
      focu: 'focus',
      tar_posi: '',
      cam1_cool: 'cooloff',
      cam1Exptime: this.getcam1Exptime()
    }
  },
  computed: {
    ...mapState({
      deviceCommand: state => state.devices.deviceCommand,
      deviceValues: state => state.devices.deviceValues
    }),
    commandlist () {
      var cmdlist = []
      var that = this
      if (this.deviceCommand[this.teles_name]) {
        cmdlist = Object.keys(this.deviceCommand[this.teles_name])
      }
      return cmdlist.filter(function (cmd) {
        return that.telescopecmd.includes(cmd)
      })
    },
    deviceStates () {
      // console.log(this.$store.state.devices.deviceStates.dome.stateStr)
      return this.$store.state.devices.deviceStates
    },
    getDomeState () {
      if (Object.keys(this.$store.state.devices.deviceStates).includes('dome')) {
        return this.$store.state.devices.deviceStates.dome.stateStr
      }
      return ''
    },
    getfocusPosition () {
      if (this.$store.getters.devlist.includes('focus')) {
        // console.log(this.deviceValues.focus.Position.value)
        return parseFloat(this.deviceValues.focus.Position.value).toFixed(3)
      }
      return ''
    }
  },
  methods: {
    devices () {
      // console.log(this.$store.getters.devlist)
      var devlist = this.$store.getters.devlist
      return devlist
    },
    getDomeStatus () {
      if (!this.devices().includes('dome')) {
        return ''
      } else {
        if (
          this.$store.state.devices.deviceStates.dome.stateStr === 'CLOSE'
        ) {
          return 'Close'
        } else {
          return 'Open'
        }
      }
    },
    async domecmd () {
      try {
        let url = API.apiCmd({
          device: 'dome',
          cmd: this.domestatus
        })
        let response = await httpApiConfig.fetch(url)
        console.log(response)
      } catch (error) {
        console.error(error)
      }
    },
    getArgsList () {
      this.argslist = []
      if (this.devices().includes(this.teles_name)) {
        if (
          Object.keys(this.deviceCommand[this.teles_name]).includes(
            this.curr_command
          )
        ) {
          var argsnamelist = Object.keys(
            this.deviceCommand[this.teles_name][this.curr_command].args
          )
          for (let index = 0; index < argsnamelist.length; index++) {
            this.argslist.push({
              name: argsnamelist[index],
              value: ''
            })
            // console.log(this.argslist)
          }
        }
      }
      return this.argslist
    },
    async cmdTelescope () {
      if (this.curr_command === '') {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('nochoiceCMD')
        })
      } else {
        var args = ''
        var command = ''
        if (this.argslist.length > 0) {
          for (let index = 0; index < this.argslist.length; index++) {
            if (this.argslist[index].value !== '') {
              args += ',' + this.argslist[index].value
            }
          }
          command = this.curr_command + args
        } else {
          command = this.curr_command
        }
        try {
          let url = API.apiCmd({
            device: 'telescope',
            cmd: command
          })
          let response = await httpApiConfig.fetch(url)
          if (response.status === 200 || response.status === 304) {
            console.log(Object.keys(this.argslist))
            this.$q.notify({
              color: 'positive',
              textColor: 'white',
              position: 'center',
              timeout: 1500,
              message: this.$t('cmdsend')
            })
          } else {
            this.$q.notify({
              color: 'red-5',
              textColor: 'white',
              position: 'center',
              timeout: 1500,
              message: this.$t('cmdsenderr')
            })
          }
        } catch (error) {
          console.error(error)
        }
      }
    },
    async findHome () {
      try {
        let url = API.apiCmd({
          device: 'focus',
          cmd: 'Home'
        })
        let response = await httpApiConfig.fetch(url)
        console.log('res', response)
        if (response.status === 200) {
          console.log(Object.keys(this.argslist))
          this.$q.notify({
            color: 'positive',
            textColor: 'white',
            position: 'center',
            timeout: 1500,
            message: this.$t('cmdsend')
          })
        }
      } catch (error) {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('cmdsenderr')
        })
        console.error(error)
      }
    },

    async setPos () {
      try {
        let url = API.apiCmd({
          device: 'focus',
          cmd: 'SetPos,' + this.tar_posi
        })
        let response = await httpApiConfig.fetch(url)
        if (response.status === 200 || response.status === 304) {
          this.$q.notify({
            color: 'positive',
            textColor: 'white',
            position: 'center',
            timeout: 1500,
            message: this.$t('cmdsend')
          })
        }
      } catch (error) {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('cmdsenderr')
        })
        console.error(error)
      }
    },
    async focusStop () {
      try {
        let url = API.apiCmd({
          device: 'focus',
          cmd: 'Stop'
        })
        let response = await httpApiConfig.fetch(url)
        if (response.status === 200 || response.status === 304) {
          this.$q.notify({
            color: 'positive',
            textColor: 'white',
            position: 'center',
            timeout: 1500,
            message: this.$t('cmdsend')
          })
        }
      } catch (error) {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('cmdsenderr')
        })
        console.error(error)
      }
    },
    async domeStop () {
      try {
        let url = API.apiCmd({
          device: 'dome',
          cmd: 'Stop'
        })
        let response = await httpApiConfig.fetch(url)
        if (response.status === 200 || response.status === 304) {
          this.$q.notify({
            color: 'positive',
            textColor: 'white',
            position: 'center',
            timeout: 1500,
            message: this.$t('cmdsend')
          })
        }
      } catch (error) {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('cmdsenderr')
        })
        console.error(error)
      }
    },
    async cameraCool () {
      try {
        let url = API.apiCmd({
          device: 'CAM1',
          cmd: this.cam1_cool
        })
        let response = await httpApiConfig.fetch(url)
        if (response.status === 200) {
          this.$q.notify({
            color: 'positive',
            textColor: 'white',
            position: 'center',
            timeout: 1500,
            message: this.$t('cmdsend')
          })
        }
      } catch (error) {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('cmdsenderr')
        })
        console.error(error)
      }
    },
    async camExpose () {
      try {
        let url = API.apiCmd({
          device: 'CAM1',
          cmd: 'expose'
        })
        let response = await httpApiConfig.fetch(url)
        if (response.status === 200) {
          this.$q.notify({
            color: 'positive',
            textColor: 'white',
            position: 'center',
            timeout: 1500,
            message: this.$t('cmdsend')
          })
        }
      } catch (error) {
        this.$q.notify({
          color: 'red-5',
          textColor: 'white',
          position: 'center',
          timeout: 1500,
          message: this.$t('cmdsenderr')
        })
        console.error(error)
      }
    },
    getlabel () {
      if (this.cam1_cool === 'cooloff') {
        return 'cool off'
      } else {
        return 'cool on'
      }
    },
    getcam1Exptime () {
      if (this.$store.getters.devlist.includes('CAM1')) {
        return parseFloat(
          this.$store.state.devices.deviceValues.CAM1.EXPTIME.value
        ).toFixed(3)
      }
    },
    getcam1ColorMode () {
      if (this.$store.getters.devlist.includes('CAM1')) {
        return parseFloat(
          this.$store.state.devices.deviceValues.CAM1.ColorMode.value
        ).toFixed(3)
      }
    },
    getcam1TempHot () {
      if (this.$store.getters.devlist.includes('CAM1')) {
        return parseFloat(
          this.$store.state.devices.deviceValues.CAM1.TempHot.value
        ).toFixed(3)
      }
    },
    getcam1TempCold () {
      if (this.$store.getters.devlist.includes('CAM1')) {
        return parseFloat(
          this.$store.state.devices.deviceValues.CAM1.TempCold.value
        ).toFixed(3)
      }
    },
    getcam1TargetTemp () {
      if (this.$store.getters.devlist.includes('CAM1')) {
        return parseFloat(
          this.$store.state.devices.deviceValues.CAM1.TargetTemp.value
        ).toFixed(3)
      }
    },
    async changeExptime () {
      let url = API.apiSet({
        device: 'CAM1',
        name: 'EXPTIME',
        value: this.cam1Exptime
      })
      try {
        let res = await httpApiConfig.fetch(url)
        console.log('set ok', res.data)
      } catch (err) {
        console.error('error:', err)
        this.errMsg(err)
      }
    }
  }
}
</script>

<style>
</style>
`

**Comment by pdanpdan** [comment]
Please put the relevant code in a codepen. Or give us an url where we can test it.

**Comment by pdanpdan** [comment]
Please try with the latest release (v1.5.8) and report back if the problem is fixed. Thank you.

**Comment by nicolaslima321** [comment]
Hi guys!

I'm also having trouble on display of my quasar buttons.. I building quasar applications using electron. My OS is Linux (Fedora 30).. I updated my project to Quasar v1.5.8 have a couple of minutes..

I searched for this component at docs, and the samples buttons at docs are on the same state of my project.

![image](https://user-images.githubusercontent.com/23743072/70565107-32282400-1b70-11ea-9296-8c2011aa7976.png)

Best Regards!

**Comment by pdanpdan** [comment]
@nicolaslima321 What browser?

**Comment by nicolaslima321** [comment]
@pdanpdan at Google Chrome, on project Electron is using Chromium

**Comment by pdanpdan** [comment]
Can you please refresh the browser and check if the docs look ok?

**Comment by nicolaslima321** [comment]
Actually.. Now i saw i had missing updates on my browser, apologize me for not had attention

**Comment by nicolaslima321** [comment]
@pdanpdan i tried to upgrade again with `npm upgrade`, then i remove package-json.lock file and node_modules folder, and tried `yarn install`  then running `quasar dev -m electron` the buttons seems the same of my previously screenshot, tried then to remove yarn.lock, node_modules folder and running `npm install` but the same happenned

**Comment by pdanpdan** [comment]
@nicolaslima321 please do a `quasar info` in the project folder and post the output.
Also if you can add (in code block) some code for the buttons you use and a screenshot of how they look.

**Comment by ed-yee** [comment]
I just upgraded my project to the latest (quasar 1.5.8, @quasar/app 1.3.7). I notice the button has 0 height:
![image](https://user-images.githubusercontent.com/24571355/70597434-46792900-1c23-11ea-8784-8364e4b21a5f.png)

![image](https://user-images.githubusercontent.com/24571355/70597563-9eb02b00-1c23-11ea-886c-e1c3cea97ca6.png)

It seems like the size property is being ignored. Once I specify a height (style="height: 2.5em"), it looks a bit better.
![image](https://user-images.githubusercontent.com/24571355/70597818-49284e00-1c24-11ea-84c3-ed383f1c8f25.png)

**Comment by ed-yee** [comment]
Q-btn in q-toolbar seems to be okay
![image](https://user-images.githubusercontent.com/24571355/70598096-031fba00-1c25-11ea-973b-2f5dde6cd514.png)

Q-btn in q-menu has no height
![image](https://user-images.githubusercontent.com/24571355/70598223-50039080-1c25-11ea-830f-e02ea2f2381d.png)

Very strange

**Comment by pdanpdan** [comment]
I need something where I can inspect and reproduce this.

**Comment by ed-yee** [comment]
Sorry, I can't share my project repo - it is internal. I'm creating a new Quasar Electron project and see if I can replicate the problem.

**Comment by ryhn** [comment]
Hi, 
Version:  1.5.8, 
Browser: Chrome Desktop 
New css attribute disrupts button views. It is fixed when this attribute disabled
 `
.q-btn {
...
...
height: fit-content
}`

**Comment by pdanpdan** [comment]
@ryhn What version of Crome?

**Comment by ryhn** [comment]
Chrome Version:  70.0.3538.77 (Official Build) (64-bit)
OS: Ubuntu

**Comment by pdanpdan** [comment]
October 16, 2018 :)
Ok, i'll try something and post here instructions on how to test.

**Comment by jean-moldovan** [comment]
![Screen Shot 2019-12-11 at 11 10 23 AM](https://user-images.githubusercontent.com/3635352/70603083-dfe61200-1c06-11ea-8647-77864e3671d2.png)

Buttons are not displayed correctly after todays quasar upgrade

Reproduced on official quasar jsfiddle https://jsfiddle.net/ntmz604b/

Chrome Version 77.0.3865.90 (Official Build) (64-bit) (Mac OS)

**Comment by ryhn** [comment]
No problem on Chromium browser version 78.0.3904.108 (Official Build) Built on Ubuntu (64-bit)

**Comment by pdanpdan** [comment]
For testing the fix please replace in package.json `"quasar": "^1...."` with `"quasar": "https://github.com/pdanpdan/quasar#quasar-v1.5.8-gitpkg"` and report here if it fixes the problem.

**Comment by huy-tran** [comment]
🐫

**Comment by huy-tran** [comment]
I'M MELEE.

**Comment by rstoenescu** [comment]
Fix will be available in "quasar" v1.5.8.
But please test with `"quasar": "https://github.com/pdanpdan/quasar#quasar-v1.5.8-gitpkg"` until the release to ensure it catches all cases. Thanks.

**Comment by pratik227** [comment]
@rstoenescu 
![screenshot-quasar dev-2019 12 11-15_18_47](https://user-images.githubusercontent.com/34883558/70611794-c99e7d00-1c2b-11ea-8ef7-016fa3115f20.png)

This has been fixed or not?

![screenshot-quasar dev-2019 12 11-15_15_12](https://user-images.githubusercontent.com/34883558/70611842-d9b65c80-1c2b-11ea-901b-b6930c406fbe.png)

**Comment by mboeni** [comment]
Just tested it again. It does not fix the issue for my electron app. See https://forum.quasar-framework.org/topic/4883/messed-up-button-positions-since-last-quasar-update/7

**Comment by ed-yee** [comment]
I'm also building an Electron app. (Electron 5.0.12, Chrome 73.0.3683.121) I just uninstalled and reinstalled the quasar package from the above URL. It looks the same as before. 

I notice the "bad" buttons' q-focus-helper has a 0px height. (width is correct). For the "good" buttons, q-focus-helper have proper width and height values.

![image](https://user-images.githubusercontent.com/24571355/70619628-5f4c0380-1c50-11ea-9144-18d4d30b3f44.png)

If I disable the "height: fit-content", it fixes all "bad" buttons in my app.
![image](https://user-images.githubusercontent.com/24571355/70621564-daafb400-1c54-11ea-9557-5260a829f55a.png)

**Comment by pdanpdan** [comment]
Hello all. I need a new test.

For testing the fix please replace in package.json "quasar": "^1...." with "quasar": "https://github.com/pdanpdan/quasar#quasar-v1.5.8-test.1-gitpkg" and report here if it fixes the problem.

Cleanup node_modules and yarn.lock / package-lock.json and do yarn/npm install.

**Comment by mboeni** [comment]
On it...give me a few mins...

**Comment by mboeni** [comment]
Yep, works. I can confirm the fix for my app.

**Comment by rstoenescu** [comment]
Fixed in “quasar” v1.5.9.
Thanks for testing!

**Comment by yinchuanyue** [comment]
@pdanpdan Thank you, I just upgraded quasar to v1.5.9, and the problem disappeared.

**Comment by louisameline** [comment]
I just saw the fix that was brought for this issue, and now my `height` on buttons is broken, it's overriden by this:
 ```css
.row > .q-btn height: 100%
```
Was this the right decision? Should a button in a flex container really take the height of its parent?
Is the original issue worth forcing us to write more complicated CSS to set the height of a button?
I think that such a basic need should not require me to override a `parent > child` set of rules nor use `!important`.

And for some reason, setting a height on the row itself cuts the button:
![image](https://user-images.githubusercontent.com/371814/71185296-76f04100-227b-11ea-93fe-95ccd80bfdb7.png)

Could this be reverted by any chance? Thank you

**Comment by pdanpdan** [comment]
@louisameline Do you have some html/style to see the problem?

**Comment by louisameline** [comment]
Only the `height` getting overriden : https://codepen.io/Louis99/pen/abzJNPN

I always felt the `size` property of buttons had a misleading name, it's just the font size.
Not handy when you want to be in control of the button size.

**Comment by louisameline** [comment]
And my button getting cut above is just because of some margin on it. The container was supposed to adjust to the size of the button, not the other way around.

**Comment by louisameline** [comment]
Just curious, I'll ask the obvious question, why not let people upgrade their version of Chrome and let Q-Button `height` alone?

**Comment by louisameline** [comment]
Hi, any news on this is issue? Will you reopen or do you want me to open a new one so the regression can be fixed? Thanks
