### ISSUE TITLE
Quasar CLI Typescript + IE11 Error

### ISSUE THREAD

**Issue by dgallets** [quasarframework/quasar#6856]
Run quasar create.
Create a new project that uses Typescript and targets IE11. 
Run quasar dev.

IE console displays error:
SCRIPT1010: Expected identifier
app.js (1084,1)

The generated `tsconfig.json` extends `@quasar/app/tsconfig-preset` which targets ES6.

One solution is to modify `tsconfig.json` to target ES5 if IE11 is selected by adding `"target": "es5"` to `compilerOptions`.

**Comment by IlCallo** [comment]
@dgallets can you confirm the issue is fixed, by launching this command and checking everything works as expected?

`quasar create <your-project name> --kit IlCallo/quasar-starter-kit --branch fix-ie-tsconfig`

**Comment by rstoenescu** [comment]
The PR has been merged into the starter kit, so you can now try directly with `quasar create <proj-name>`.

Please reopen if problem persists. Thank you.
