### ISSUE TITLE
htmlFileName - @quasar/app-v1.8.x

### ISSUE THREAD

**Issue by kevinmelo** [quasarframework/quasar#7078]
**Describe the bug**
After quasar 1.8.x if you try use `htmlFileName` inside `quasar.conf.js > build` the application will not work.

**To Reproduce**
1. Create a new project with `quasar create`
2. Execute command quasar dev to run project and verify if is working
3. Go to `quasar.confg.js` and add inside build `htmlFileName: 'teste.html'`
4. Application will not work anymore

**Expected behavior**
Expected application work after use `htmlFileName`

**Additional context**
I was digging in commits in 1.8.0 (when stop working) and i see a change in file app/lib/webpack/inject.html.js before the filename inside `chain.plugin` was fixed `index.html` if was DEV, but after commit, he use the `htmlFileName` in `quasar.conf.js`

My application is in spa mode

**Comment by rstoenescu** [comment]
Hi, What do you mean by "will not work"?

**Comment by rstoenescu** [comment]
Also, what mode are you building with? More details pls.

**Comment by kevinmelo** [comment]
@rstoenescu the appplication will throw error 404, and will not acces any route (try the **To reproduce step** it's easy to reproduce.

Like i said, i'm building with `spa` mode

**Comment by pdanpdan** [comment]
I suppose you are using router history mode?

**Comment by kevinmelo** [comment]
@pdanpdan yes

**Comment by rstoenescu** [comment]
Fix available in "@quasar/app" v1.8.9.

**Comment by kevinmelo** [comment]
@rstoenescu and @pdanpdan still getting same error on `router history mode` when trying to access direct an route that is not `localhost:8080` like 'localhost:8080/test'

**Comment by rstoenescu** [comment]
Found the culprit.

**Comment by rstoenescu** [comment]
Fixed in "@quasar/app" v1.8.10.
