### ISSUE TITLE
QEditor: force use of paragraphs

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/quasar#7804]
I figured out how to use `<p>` instead of `<div>` by changing the definition:
```javascript
data() {
    return {
        definitions: {
            p: {
                cmd: 'formatBlock',
                param: 'P',
                icon: this.$q.iconSet.editor.heading,
                tip: this.$q.lang.editor.paragraph,
            },
        },
        toolbar: [
            ['left', 'center', 'right', 'justify'],
            ['bold', 'italic', 'strike', 'underline', 'link'],
            [
                {
                    label: this.$q.lang.editor.formatting,
                    icon: this.$q.iconSet.editor.formatting,
                    list: 'no-icons',
                    options: ['h2', 'h3', 'p'],
                },
            ],
            ['unordered', 'ordered'],
            ['removeFormat', 'fullscreen', 'viewsource'],
        ],
    }
},
```
How do I force the editor to use the paragraph formatting when not explicitly marked as `<h2>` or `<h3>`, and surround the first text with `<p>` aswell?

**Comment by pdanpdan** [comment]
I think this is solved together with #7809

**Comment by smbt** [comment]
I feel like the second part of the issue 
>  and surround the first text with &lt;p&gt; aswell

has still not been adressed. I´m facing the issue that my first entries are placed outside the <p> tag. Is this intended behaviour and if yes, does anyone know a clean way to work around this? Thanks a lot.

![qeditor](https://user-images.githubusercontent.com/29025263/105339161-aa1ea580-5bdc-11eb-8b07-e2f5a4333920.gif)

**Comment by FrittenKeeZ** [comment]
@smbt oh boy, you just re-opened a whole can of worms 🤯 

I ended up cleaning text from the editor, to prevent unintentional behaviour like paragraphs surrounding lists.

In the component wrapper itself, I have this input handling:
```javascript
computed: {
    valueSync: {
        get: function() {
            return this.value || ''
        },
        set: function(value) {
            const isViewingSource = this.$refs.editor.isViewingSource
            const insertParagraph = value && !!value.length && !value.startsWith('<') && !isViewingSource
            if (insertParagraph) {
                value = `<p>${value}</p>`
                if (this.isViewingSource) {
                    this.$refs.editor.__setContent(value)
                }
            }
            const cleaned = cleanMarkup(value)
            if (cleaned.length !== value.length) {
                this.$refs.editor.caret.savePosition()
                this.$emit('input', cleaned)
                this.$refs.editor.caret.restorePosition(cleaned.length)
            } else {
                this.$emit('input', value)
            }
            this.isViewingSource = isViewingSource
        },
    }
},
```
Helper functions in `js/TextUtils.js`:
```javascript
export function removeEmptyTags(html) {
    const regex = /<(?!\/)([^>]+)><\/([^>]+)>/gi
    // Ensure only identical pairs are matched.
    const matches = [...html.matchAll(regex)].filter(match => match[1] === match[2])
    if (matches.length > 0) {
        return removeEmptyTags(matches.reduce((cleaned, match) => cleaned.replace(match[0], ''), html))
    }
    return html
}

export function cleanMarkup(html) {
    const replaced = html
        .replace(/<\/?span([^>]*)>/gi, '') // Remove span tags.
        .replace(/ style="[^"]+"/gi, '') // Remove all style attributes.
        .replace(/<(\/)?div>/gi, '<$1p>') // Replace all divs with paragraphs.
        .replace(/<p><([ou]l)>/gi, '<$1>') // Remove all paragraphs surrounding a list
        .replace(/<\/([ou]l)><\/p>/gi, '</$1>')
    return removeEmptyTags(replaced) // Remove all empty tag pairs.
}
```

**Comment by smbt** [comment]
Thanks a lot for the code. I will give this another try. And sorry for digging out old issues.

**Comment by saibrok** [comment]
> I feel like the second part of the issue
> 
> > and surround the first text with <p> aswell
> 
> has still not been adressed. I´m facing the issue that my first entries are placed outside the
> 
> tag. Is this intended behaviour and if yes, does anyone know a clean way to work around this? Thanks a lot.

Yes, it's only been 2 years, but I have the same problem. `hello<p>hello</p>`. In addition to the paragraph-tag option, I found a solution in initializing the editor filled with `<p><br></p>`

**Comment by dsl101** [comment]
Can't believe this is still a thing... But @FrittenKeeZ I updated your code for Vue3 / Quasar2, and it's mostly working nicely. One problem I have (not sure if you also saw this on the original version) is that if you start with an empty editor, change to, e.g. H1, type a word then press Return, the caret stays on the same line, not moving to a new line. The new `<p>` tag is created, but the caret doesn't follow. It seems there's no difference in the caret position between the end of that line and the start of the next (both 5 in this example). But changing the emitted value to `cleaned` does something to upset the caret positioning...

![Image](https://github.com/user-attachments/assets/39ba41db-36a4-4d2d-8c9f-c720e75305f8)

```vue
<template>
  <q-editor
    ref="editorRef"
    :modelValue="model"
    paragraph-tag="p"
    :toolbar="editorConfig.toolbar"
    v-bind="$attrs"
    @update:modelValue="edit"
  />
</template>

<script setup>
  import { ref } from 'vue'
  import { editorConfig, firestoreDebounce } from 'src/defaults'
  import { debounce } from 'quasar'

  const editorRef = ref()
  const model = defineModel({ type: String })
  const emit = defineEmits([ 'update:modelValue' ])
  const isViewingSourceRef = ref()

  const edit = value => {
    const editorVM = editorRef.value.caret.eVm
    const isViewingSource = editorVM.isViewingSource.value
    const insertParagraph = value && !!value.length && !value.startsWith('<') && !isViewingSource

    if (insertParagraph) {
      value = `<p>${value}</p>`
      if (isViewingSourceRef.value) {
        editorVM.setContent(value)
      }
    }
    const cleaned = cleanMarkup(value)
    if (cleaned.length !== value.length) {
      editorRef.value.caret.savePosition()
      emit('update:modelValue', cleaned)
      editorRef.value.caret.restorePosition(cleaned.length)
    } else {
      emit('update:modelValue', value)
    }
    isViewingSourceRef.value = isViewingSource
  }

  function removeEmptyTags (html) {
    const regex = /<(?!\/)([^>]+)><\/([^>]+)>/gi
    // Ensure only identical pairs are matched.
    const matches = [...html.matchAll(regex)].filter(match => match[1] === match[2])
    if (matches.length > 0) {
        return removeEmptyTags(matches.reduce((cleaned, match) => cleaned.replace(match[0], ''), html))
    }
    return html
  }
  function cleanMarkup (html) {
    const replaced = html
      .replace(/<\/?span([^>]*)>/gi, '') // Remove span tags.
      .replace(/ style="[^"]+"/gi, '') // Remove all style attributes.
      .replace(/<(\/)?div>/gi, '<$1p>') // Replace all divs with paragraphs.
      .replace(/<p><([ou]l)>/gi, '<$1>') // Remove all paragraphs surrounding a list
      .replace(/<\/([ou]l)><\/p>/gi, '</$1>')
    return removeEmptyTags(replaced) // Remove all empty tag pairs.
  }
</script>
```

**Comment by FrittenKeeZ** [comment]
@dsl101 I have abandoned the use of custom WYSIWYG editors in favor of TipTap.
