### ISSUE TITLE
Quasar App 2.2.3 problems with webpack types

### ISSUE THREAD

**Issue by tgrelka** [quasarframework/quasar#8689]
**Describe the bug**
I noticed in a different project that @quasar/app 2.2.3 suddenly spits out a ton of webpack type errors.
I then tried creating a brand new project with @quasar/cli 1.1.3 and Typescript support.

Upon running `quasar d`, I was presented with a page - and a huge error log, mostly repeats of
```
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(32,3):
TS2305: Module '"tapable"' has no exported member 'Tapable'.
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1062,23):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1070,30):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1066,27):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
```
as well as some others, all webpack- and type-related.

**Codepen/jsFiddle/Codesandbox (required)**
Not sure how to present this in a fiddle...

**To Reproduce**
1. Create a new project with Quasar CLI and enable Typescript support.
2. Run `quasar d`
3. See error

**Expected behavior**
Expecting correct webpack types out of the box and no errors

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 1.15.9
@quasar/app Version: 2.2.3
Quasar mode: 

  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 14.15.4
NPM: 7.6.2
Yarn: 1.22.10
Browsers: -/-
iOS: -/-
Android: -/-
Electron: -/-

**Log Output**
```
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1070,30):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1071,24):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1080,33):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1081,27):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1082,37):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1083,44):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1084,47):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1085,28):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1086,30):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1087,24):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1088,25):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1089,34):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1090,25):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1091,31):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1092,36):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1093,35):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1094,34):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1095,40):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1096,33):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1097,36):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1098,38):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1099,36):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1100,28):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1101,25):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1102,27):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1103,25):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1104,29):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1105,23):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1106,32):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1107,22):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1108,29):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1109,38):
TS2314: Generic type 'HookMap<H>' requires 1 type argument(s).
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1110,48):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1111,44):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1112,26):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1121,28):
TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1122,27):
TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1123,33):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1124,27):
TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1144,21):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1145,19):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1147,40):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1148,35):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1149,43):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1152,23):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1154,35):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1155,30):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1156,38):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1171,27):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1190,25):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1191,24):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1197,33):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1198,40):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1199,32):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1204,31):
TS2707: Generic type 'AsyncSeriesHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1210,33):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1211,24):
TS2707: Generic type 'AsyncSeriesHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1219,33):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1220,28):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1224,43):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1225,38):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1226,46):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1239,27):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1240,22):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1241,32):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1242,28):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1243,24):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1244,27):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1258,22):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1259,21):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1260,21):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1261,22):
TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1262,19):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1356,25):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1358,29):
TS2707: Generic type 'AsyncSeriesHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1374,25):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1375,26):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1376,31):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1379,26):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1399,25):
TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@quasar/app/node_modules/@types/webpack/index.d.ts(1466,24):
TS2707: Generic type 'SyncBailHook<T, R, AdditionalOptions>' requires between 2 and 3 type arguments.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@types/terser-webpack-plugin/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@types/terser-webpack-plugin/index.d.ts(8,10):
TS2305: Module '"webpack"' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@types/webpack-bundle-analyzer/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@types/webpack-bundle-analyzer/index.d.ts(9,10):
TS2305: Module '"webpack"' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/@types/webpack-bundle-analyzer/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/@types/webpack-bundle-analyzer/index.d.ts(76,31):
TS2702: 'Stats' only refers to a type, but is being used as a namespace here.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(57,41):
TS2694: Namespace 'exports' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(66,28):
TS2694: Namespace 'exports' has no exported member 'ExternalsElement'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(66,55):
TS2694: Namespace 'exports' has no exported member 'ExternalsElement'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(75,24):
TS2694: Namespace 'exports' has no exported member 'Options'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(78,31):
TS2694: Namespace 'exports' has no exported member 'Options'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(81,53):
TS2694: Namespace 'exports' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(101,49):
TS2694: Namespace 'exports' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(104,68):
TS2694: Namespace 'exports' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(213,26):
TS2694: Namespace 'exports' has no exported member 'Options'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(238,57):
TS2694: Namespace 'exports' has no exported member 'ResolvePlugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(249,48):
TS2694: Namespace 'exports' has no exported member 'ResolvePlugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(261,44):
TS2694: Namespace 'exports' has no exported member 'Condition'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(262,44):
TS2694: Namespace 'exports' has no exported member 'Condition'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(266,25):
TS2694: Namespace 'exports' has no exported member 'Condition'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(266,45):
TS2694: Namespace 'exports' has no exported member 'Condition'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(284,34):
TS2694: Namespace 'exports' has no exported member 'Condition'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(284,54):
TS2694: Namespace 'exports' has no exported member 'Condition'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(292,58):
TS2694: Namespace 'exports' has no exported member 'Plugin'.
C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts
ERROR in C:/Users/Tim Grelka/Projects/clientnew/node_modules/webpack-chain/types/index.d.ts(380,69):
TS2694: Namespace 'exports' has no exported member 'Plugin'.
```

**Comment by JeepayJipex** [comment]
Same thing for me here,
Using quasar dev in Electron mode on a fresh install :
- With typescript support
- Vue router
- Vuex
- Eslint (standard)

Output of my quasar info (if it can help) :

```
❯ quasar info

Operating System - Linux(5.4.0-67-generic) - linux/x64
NodeJs - 12.20.0

Global packages
  NPM - 6.14.8
  yarn - 1.22.4
  @quasar/cli - 1.1.3
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 1.15.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.2.3 -- Quasar Framework local CLI
  @quasar/extras - 1.10.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.12 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.6.0 -- state management for Vue.js
  electron - 9.4.4 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.13.13 -- Babel compiler core.
  webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by jonganej** [comment]
Also facing the same issue. 

Might be a dependency conflict as `@types/tapable` (see the screenshot result of `npm ls @types/tapable`). Essentially, the newer version (v2.2.0) gets installed but the `html-webpack-plugin` depends on an older version which might have a different definition for many classes.
![types_tapable_dependencies](https://user-images.githubusercontent.com/4180997/112828797-7c4c5600-9090-11eb-87f2-fd2a4b3130ed.PNG)

**Comment by hawkeye64** [comment]
If you are not already using it try `yarn`. Make sure to remove `node_modules` folder and `package-lock.json` first.

**Comment by rainer9202** [comment]
Is anything new known about this bug ??? solutions ?? chances of it being fixed in the future?

**Comment by jonganej** [comment]
> 
> 
> If you are not already using it try `yarn`. Make sure to remove `node_modules` folder and `package-lock.json` first.

That unfortunately did not solve it. I'm running my dev environment on containers using yarn for dependency management so that's probably not the issue.

**Comment by hawkeye64** [comment]
Have you tried adding a `resolutions` to your package.json?

**Comment by eyedean** [comment]
I am running into a similar issue with `vue-router`:
```
node_modules/vue-router/types/vue.d.ts:17:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'router' must be of type 'VueRouter | undefined', but here has type 'VueRouter | undefined'.

17     router?: VueRouter
       ~~~~~~

  node_modules/@quasar/app/node_modules/vue-router/types/vue.d.ts:17:5
    17     router?: VueRouter
           ~~~~~~
    'router' was also declared here.
```

The problem is I am on `vue-router` 3.4, since I am using the [Navigation Failures](https://router.vuejs.org/guide/advanced/navigation-failures.html) in my project.  However, @quasar/app is on  a **fixed** version of 3.2.0 as of the [package.json](https://github.com/quasarframework/quasar/blob/dev/app/package.json#L109).  This mismatch causes Typescript to complain because the interface type of `VueRouter` is different in 3.2 vs 3.4.

I am not using `yarn`/`resolutions` and I am not planning to.  I believe using "fixed" (or as they called "pinned" version of packages) can minimize the bugs that are filed with Quasar when a third-party library updates their package and things break.  However, it causes problems like this, as well as increased size of the final artifact due to duplicate versions.  [This article](https://the-guild.dev/blog/how-should-you-pin-dependencies-and-why) has a good summary on pros and costs of keeping a pinned version of dependencies, in a library like Quasar.

If the Quasar team's strategy is going to remain "pinned" version, maybe you can add a section/tag for "library update requests" in "issues".  I have been waiting for this error to go away on its own when `vue-router` is upgraded, but apparently it hasn't happened [since 10 months ago](https://github.com/quasarframework/quasar/commit/f23efbbe05efc3e60ff901c4f39e931e57c8a7ee) (the last version change on vue-router).  So, any idea on how to prevent this or handle it better in future for other packages?

PS. Do I need to open a separate ticket for `vue-router` upgrade to 3.4 or 3.5 in order to get my issue fixed?

PPS. Quasar is awesome!

**Comment by ayayui** [comment]
Same issue and  I try to add skipLibCheck option to tsconfig.json to ignore it.
```
  "compilerOptions": {
    "skipLibCheck": true
  },
```

**Comment by IlCallo** [comment]
@eyedean 
> PS. Do I need to open a separate ticket for vue-router upgrade to 3.4 or 3.5 in order to get my issue fixed?

Yes, it's a different problem than this one. AFAIK we haven't upgrade vue-router because of problems introduced in new versions, but something may have changed. That said, we cannot guarantee Quasar to work if you use a different version from the one provided `@quasar/app` package, and we periodically upgrade deps if they don't cause more trouble than the features they add. Pinning is a way for us to protect users 

-----

**Coming to the original problem with webpack types**
Seems like every update of any webpack-related package will bring a breaking change of sort, since the type graph is too nested and entrenched, yet managed by community PRs via `@types/*` packages.
Webpack 5 should finally serve it's own types and reduce a bit the complexity.

Seems like the issue has already been tackled upstream and let's hope it's the last time it happens. Testing now it upgrading fix the problem.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51712

In the meantime, `skipLibCheck` should to be easiest workaround

**Comment by rstoenescu** [comment]
Fix will be available in "@quasar/app" v2.2.4.
