### ISSUE TITLE
QInfiniteScroll spinner is shown if stopped

### ISSUE THREAD

**Issue by buccfer** [quasarframework/quasar#888]
Quasar: 0.14.3
OS: Ubuntu 16.04 LTS
Node: v7.5.0
NPM: v4.1.2
Browsers: Any

### What did you get as the error?
The spinner still shows if the infinite scroll is stopped.

### What were you expecting?
The spinner shouldn't be displayed if infinite scroll is stopped.

### What steps did you take, to get the error?
1. Use the infinite scroll.
2. Stop it by using this.$refs.infiniteScroll.stop()
3. Check the spinner is showing.

Maybe a side effect of #887?

**Comment by buccfer** [comment]
Well the problem was:

```html
<q-infinite-scroll :handler="loadPatients" :offset="10" ref="infiniteScroll">
  <!-- other code -->
  <div class="row justify-center">
    <div class="col-auto">
      <q-spinner-puff slot="message" :size="40" color="secondary"></q-spinner-puff>
    </div>
  </div>
</q-infinite-scroll>
```

Fixed by moving the slot upwards.

```html
<q-infinite-scroll :handler="loadPatients" :offset="10" ref="infiniteScroll">
  <!-- other code -->
  <div slot="message" class="row justify-center">
    <div class="col-auto">
      <q-spinner-puff :size="40" color="secondary"></q-spinner-puff>
    </div>
  </div>
</q-infinite-scroll>
```

**Comment by immortalx** [comment]
This is still happening for me on 0.14.7

After using this.$refs.infiniteScroll.stop() the spinner is still showing.
Executing stop() this.$refs.infiniteScroll.working is set to false but this.$refs.infiniteScroll.fetching is still true

All the data has been loaded, everything seems to work fine but the spinner is always showing since v-show is tied to the fetching variable

**Comment by buccfer** [comment]
@immortalx here you have a working sample

```
<template>
  <q-infinite-scroll :handler="loadPatients" :offset="10" ref="infiniteScroll">
    <div class="row">
      <div v-for="(patient, index) in patients" :key="index" class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <patient-details-card :patient="patient"></patient-details-card>
      </div>
    </div>
    <div slot="message" class="row justify-center">
      <div class="col-auto">
        <q-spinner-puff :size="40" color="secondary"></q-spinner-puff>
      </div>
    </div>
  </q-infinite-scroll>
</template>

<script>
import {
  QInfiniteScroll,
  QSpinnerPuff
} from 'quasar'

import PatientDetailsCard from './PatientDetailsCard'
import PatientService from '../../services/patient'

const PAGE_SIZE = 12

export default {
  components: {
    PatientDetailsCard,
    QInfiniteScroll,
    QSpinnerPuff
  },
  data () {
    return {
      patients: []
    }
  },
  methods: {
    loadPatients (index, done) {
      const params = {
        offset: (index - 1) * PAGE_SIZE,
        limit: PAGE_SIZE
      }
      PatientService.list(params)
        .then(({ data }) => {
          const { results, total } = data
          this.patients = this.patients.concat(results)
          const { offset, limit } = params
          if (offset + limit >= total) {
            // We just got the last page. Stop infinite scroll
            this.$refs.infiniteScroll.stop()
          }
          done()
        })
        .catch(() => {
          this.$refs.infiniteScroll.stop()
          done()
        })
    }
  }
}
</script>
```

Please also check the PR that fixes the docs.. https://github.com/quasarframework/quasar-play/pull/26.

**Comment by immortalx** [comment]
@buccfer That was fast, thank you! I got it working now thanks to your example.
My issue was calling the stop() and done() when i got the last page. From the docs and the source example i was under impression that only done() was needed.

Once again, thank you very much.
