### ISSUE TITLE
The q-input component has a bug when inputting Chinese in the Mac Safari browser

### ISSUE THREAD

**Issue by yangjiafu** [quasarframework/quasar#9179]
When I use the q-input component to input Chinese in the mac Safari browser, there will be repeated Chinese pinyin
https://user-images.githubusercontent.com/28332458/117227421-58c3ba80-ae49-11eb-9f7a-b16cde53c1c0.mov

This is the correct effect on the Chrome browser
https://user-images.githubusercontent.com/28332458/117227637-dc7da700-ae49-11eb-9251-0118697799c7.mov

**Comment by pdanpdan** [comment]
Hello.
Can you please try if it's fixed here: https://pdanpdan.github.io/quasar-docs/vue-components/input ?

**Comment by yangjiafu** [comment]
Yes, the problem still exists in this version

https://user-images.githubusercontent.com/28332458/117263942-567f5180-ae85-11eb-8be4-7cff680d6a3f.mov

**Comment by hawkeye64** [comment]
So, pasting in is not the same as typing?


https://user-images.githubusercontent.com/10262924/117359128-35facb80-ae74-11eb-9438-711d6651322b.mp4

**Comment by yangjiafu** [comment]
> So, pasting in is not the same as typing?
> 
>  qinput-ime.mp4

No, I can’t use this scheme.Because my project has hundreds of input boxes.And I cannot ask the user to do this

**Comment by pdanpdan** [comment]
@yangjiafu 
I'll need a step by step procedure (in text) with what to try to reproduce.

**Comment by yangjiafu** [comment]
> @yangjiafu
> I'll need a step by step procedure (in text) with what to try to reproduce.

The steps are simple.
1. Use Chinese input method;
2. Input Chinese;
And this problem exists on both iPhone and iPad;
I found that there is no such problem in version 1.14.2;

**Comment by hawkeye64** [comment]
@yangjiafu Maybe you should explain what "Use Chinese input method" is to us Westerners :)

**Comment by pdanpdan** [comment]
I can reproduce it, I'll look into it. I think newer safari fixed some old problem it had and now the fix is breaking the correct usage

**Comment by yangjiafu** [comment]
> I can reproduce it, I'll look into it. I think newer safari fixed some old problem it had and now the fix is breaking the correct usage

I hope that you can treat this problem as soon as possible.thanks.

**Comment by pdanpdan** [comment]
Don't push it, it's just work for fun, I hate Apple products and I don't have any of my own.

**Comment by yangjiafu** [comment]
> @yangjiafu Maybe you should explain what "Use Chinese input method" is to us Westerners :)

Means the input typing method that can input Chinese characters with various combinations of English letters.
Just like the way you input Japanese or Korean.

**Comment by zknic** [comment]
I've found this problem.
quasar 1.15.5  has the correct effect
since quasar 1.15.6 this bug occurred
I'll download these two versions to compare the difference

**Comment by zknic** [comment]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/11263870/117545755-b3336580-b059-11eb-8cb2-d80c9f4b88d7.png">

**Comment by zknic** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/11263870/117547710-9439d100-b063-11eb-8242-81d8a1125404.png">
this is the problem
vue solved this problem:
https://github.com/vuejs/vue/blob/v2.3.0/src/platforms/web/compiler/directives/model.js#L151-L153
but quasar do it in his own way

**Comment by pdanpdan** [comment]
Nice catch. Can you make a PR, please

**Comment by zknic** [comment]
> ~Nice catch. Can you make a PR, please~
> Sorry, that was correct as it is.
> I'm stuck, because the problem only shows on Mac Safari (not on iPhone) so there is nothing I can do.

the problem shows on iPhone especially show on iOS 14.5.1 and iOS 13

**Comment by pdanpdan** [comment]
I have iOS 14.5.1 (latest non-beta I think) and I cannot reproduce it.
I need a step by step, detailed procedure to reproduce it on iOS:
- browser (safari)
- exact keyboard (a screenshot from iOS keyboards would help
- what keys to press

**Comment by zknic** [comment]
I made a mistake ,the problem shows on iOS 14.5, and iOS 13, I'll record a video later.

**Comment by pdanpdan** [comment]
Don't bother, a video is no help.
I only have 14.5.1.
But it sounds as a problem with iOS that is fixed.
And on Mac safari it might be a similar problem - the laptop i could use to take a look had a very old macos

**Comment by zknic** [comment]
https://youtu.be/3w6VfzGWzkI

you are right. it's an ancient problem on safari. apple fixed this problem for so many times in these years, but it still shows sometimes when the apple devices's operation system is updated. in order to solve this problem, so many web frameworks writes the code only for safari like vue. I'll try to research this problem and make it clear.

**Comment by panmenghan** [comment]
> I have iOS 14.5.1 (latest non-beta I think) and I cannot reproduce it.
> I need a step by step, detailed procedure to reproduce it on iOS:
> 
> * browser (safari)
> * exact keyboard (a screenshot from iOS keyboards would help
> * what keys to press

I tested it on iphone 8+, iOS 13.7/14.1, quasar v2, can reproduce it:

1. Using the cloud based iphone emulator: https://appetize.io/ (only need email to sign up)
2. After sign in, launching the virtual device, and change the default system language to "Chinese, Simplified"
3. Open the safari, using q-input, typing "nnn" will ouput "nnnnnn", and select the Chinese characters "你奶奶"(from the input method editor above the virtual keyboard) will ouput "nnnnnn你奶奶". The correct behavior, using native input, typing "nnn" will ouput "nnn",  and select the Chinese characters "你奶奶" (from the input method editor above the virtual keyboard) will ouput "你奶奶";

**Comment by zknic** [comment]
I finally find the problem, 
QInput.js, at line 209 
"e.target.setSelectionRange(index, index)"
cased the problem.
when js changed the SelectionRange on input element, that can break the input on safari and some iOS devices.
when I changed the function to "e.target.selectionEnd = e.target.value.length", the problem solved.
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/11263870/117606077-b2025580-b18b-11eb-87eb-6d1e3d2c731c.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/11263870/117606233-086f9400-b18c-11eb-9057-6800a23c573b.png">

**Comment by zknic** [comment]
quasar v2 beta has the same problem

**Comment by uncrelax** [comment]
Hi, guys, one of the code puzzles me.
IME input Chinese (pinyin) is actually letters,  the RegExp in the compositionupdate method is always true
![image](https://user-images.githubusercontent.com/17492155/117605663-d7db2a80-b18a-11eb-8238-2c5526cead8a.png)

**Comment by uncrelax** [comment]
![image](https://user-images.githubusercontent.com/17492155/117607402-7917b000-b18e-11eb-9a61-15fe80b646a9.png)

**Comment by zknic** [comment]
> Can you please try again here: https://pdanpdan.github.io/quasar-docs/vue-components/input ?
> Refresh so it will show v1.15.13-beta.2 (in 10 minutes)

it's still

**Comment by yangjiafu** [comment]
> Can you please try again here: https://pdanpdan.github.io/quasar-docs/vue-components/input ?
> Refresh so it will show v1.15.13-beta.2 (in 10 minutes)

this is v1.15.13-beta.1

**Comment by pdanpdan** [comment]
yep, problems with building the docs - I'll post here when it's fixed

**Comment by zknic** [comment]
> yep, problems with building the docs - I'll post here when it's fixed

if (!e || !e.target || e.target.composing === false) {

if this can help?

**Comment by pdanpdan** [comment]
ok, the docs to test should be online v1.15.13-beta.2

**Comment by zknic** [comment]
> ok, the docs to test should be online v1.15.13-beta.2

excellent!
The problem has been solved, i've tested on ios 13 and windows with "v-model.trim" and "IME input Chinese (pinyin)"

**Comment by zknic** [comment]
> > > ok, the docs to test should be online v1.15.13-beta.2
> > 
> > 
> > excellent!
> > The problem has been solved, i've tested on ios 13 and windows with "v-model.trim" and "IME input Chinese (pinyin)"
> > hello,
> > What is this link for this v1.15.13-beta.2 ?

就上面那个beat1的链接，刷新下就是2了

**Comment by yangjiafu** [comment]
> > > > ok, the docs to test should be online v1.15.13-beta.2
> > > 
> > > 
> > > excellent!
> > > The problem has been solved, i've tested on ios 13 and windows with "v-model.trim" and "IME input Chinese (pinyin)"
> > > hello,
> > > What is this link for this v1.15.13-beta.2 ?
> 
> 就上面那个beat1的链接，刷新下就是2了

哦，好的谢啦

**Comment by yangjiafu** [comment]
> > > > ok, the docs to test should be online v1.15.13-beta.2
> > > 
> > > 
> > > excellent!
> > > The problem has been solved, i've tested on ios 13 and windows with "v-model.trim" and "IME input Chinese (pinyin)"
> > > hello,
> > > What is this link for this v1.15.13-beta.2 ?
> 
> 就上面那个beat1的链接，刷新下就是2了

我发现这个框架的date.formatDate()插件函数在Safari浏览器下也会有问题
![96274EDB-14CA-4020-90FB-B31CCF019059](https://user-images.githubusercontent.com/28332458/117780898-a50c6180-b272-11eb-9c82-7c4864ce4c45.png)
如果需要转换的时间有-的话在Safari浏览器下不能直接就使用Date()函数来转换

**Comment by pdanpdan** [comment]
Please keep it in English, we cannot understand Chinese (sorry if it's not Chinese)

**Comment by hawkeye64** [comment]
> Maybe this is not a problem, the correct format should be "YYYY-MM-DDThh:mm:ss"

Having written the QCalendar app extension, I ran into this early on with Safari. It absolutely needs the 'T' separator to work. Other browsers are a bit more forgiving.

**Comment by zsjinwei** [comment]
@pdanpdan I met this issues， when to merge to master branch？

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v1.15.15 & v2.0.0-beta.17.

**Comment by chenbimo** [comment]
> > I have iOS 14.5.1 (latest non-beta I think) and I cannot reproduce it.
> > I need a step by step, detailed procedure to reproduce it on iOS:
> > 
> > * browser (safari)
> > * exact keyboard (a screenshot from iOS keyboards would help
> > * what keys to press
> 
> I tested it on iphone 8+, iOS 13.7/14.1, quasar v2, can reproduce it:
> 
> 1. Using the cloud based iphone emulator: https://appetize.io/ (only need email to sign up)
> 2. After sign in, launching the virtual device, and change the default system language to "Chinese, Simplified"
> 3. Open the safari, using q-input, typing "nnn" will ouput "nnnnnn", and select the Chinese characters "你奶奶"(from the input method editor above the virtual keyboard) will ouput "nnnnnn你奶奶". The correct behavior, using native input, typing "nnn" will ouput "nnn",  and select the Chinese characters "你奶奶" (from the input method editor above the virtual keyboard) will ouput "你奶奶";

兄弟，牛逼。这个人真是倔。
